---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {app_name}
    env: dev
    release: "1.0.0"
  name: servicedx-ui
  namespace: {ns}
spec:
  externalTrafficPolicy: Cluster
 ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {app_name}
    env: dev
    release: "1.0.0"
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
  
